### ISSUE TITLE
数字常量判断有一些错误

### ISSUE THREAD

**Issue by bbbcode** [FrozenGene/LLVMPascalCompiler#7]
1, 没有处理多个E/e
eg:  12.3e3e3
2，没有16进制处理科学计数法和点号判断
eg: $12.3
3，没有对指数E/e紧接着的数字判断
eg: 12.3e  e后面必须要是数字或者+-

**Comment by FrozenGene** [comment]
Hi， @bbbcode .
1、 Pascal 和 C / C++有些许的不同，在Pascal 90 标准中，NUMBE的表示不能跟多个e. 我贴上我参考的Pascal 90 标准 http://www.pascal-central.com/docs/iso7185.pdf ，你可以参考 6.1.5节。

2、而在Pascal 90中，其实是不支持16进制的，我是根据fpc和它的说明文档来做的，而在这当中，十六进制是不支持浮点数的，http://www.irietools.com/iriepascal/freebsd/user74.html

针对前面两点疑问，你可以测试一下fpc的行为：https://ideone.com/ideone/Index/submit/

3、这一点应该是需要加上一个诊断信息的，目前只是处理了正确的情况，我晚上回去后把这里修正一下。

感谢提交issue  ：-）

**Comment by FrozenGene** [comment]
Thanks, fixed. :-)
